trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/dist'
      artifactName: 'drop'
    displayName: 'Publish Artifact'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  environment: 'app-service-environment-rahul'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/drop'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Jan_Service_Connection_Rahul'
            appType: 'webAppLinux'
            WebAppName: 'Jan-Web-App-Rahul'
            packageForLinux: '$(System.ArtifactsDirectory)/drop/**/*.zip'